name: vitessce-tutorial-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8
  - numpy
  - pandas
  - jupyterlab
  - numba>=0.53.0
  - scanpy>=1.6.0
  - anndata==0.8.0
  - zarr
  - scipy
  - tifffile
  - scikit-image
  - h5py
  - tqdm
  - mudata
  - muon
  - pip
  - pip:
    - loompy
    - generate-tiff-offsets
    - leidenalg
    - ome-zarr==0.2.1
    - vitessce[all]==3.0.0
    - negspy
    - pybbi>=0.2.3
    - mira-multiome>=1.0.1
    - episcanpy